services:
  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lotto-jupyter
    init: true
    ipc: host
    ports:
      - "8888:8888"
    volumes:
      - ../app:/workspace
    working_dir: /workspace
    restart: unless-stopped
